import type { Locale } from "./markdown";

export const locales: { id: Locale; label: string; short: string }[] = [
  { id: "zh-Hant", label: "繁體中文", short: "繁" },
  { id: "zh-Hans", label: "简体中文", short: "简" },
  { id: "en", label: "English", short: "EN" },
  { id: "ja", label: "日本語", short: "日" },
];

export const chapterTitles: Record<Locale, string[]> = {
  "zh-Hant": [
    "古老的傳說：綁在椅子上的孩子",
    "當孩子必須離開原來的家",
    "越來越多求救，進入制度",
    "隔著布簾的急診記憶",
    "從一紙修法開始：兒福聯盟的誕生",
    "珮珮：另一間病房裡的孩子",
    "從珮珮到剴剴：制度留下的接縫",
    "外婆的眼淚：第二章前夜",
  ],
  "zh-Hans": [
    "古老的传说：绑在椅子上的孩子",
    "当孩子必须离开原来的家",
    "越来越多求救，进入制度",
    "隔着布帘的急诊记忆",
    "从一纸修法开始：儿福联盟的诞生",
    "珮珮：另一间病房里的孩子",
    "从珮珮到剴剴：制度留下的接缝",
    "外婆的眼泪：第二章前夜",
  ],
  en: [
    "An Old Legend: The Child Bound to a Chair",
    "When a Child Must Leave Home",
    "When More Calls for Help Enter the System",
    "An Emergency-Room Memory from Behind the Curtain",
    "It Began with an Amendment",
    "Peipei: A Child in Another Hospital Room",
    "From Peipei to Kaikai: The Seams Left by the System",
    "A Grandmother’s Tears: The Night Before Chapter Two",
  ],
  ja: [
    "古い伝承――椅子に縛られた子ども",
    "子どもが元の家を離れなければならないとき",
    "増え続ける助けを求める声、その先にある制度",
    "カーテン越しに残った救急室の記憶",
    "一枚の法改正案から",
    "珮珮――もう一つの病室にいた子ども",
    "珮珮から剴剴へ――制度に残された継ぎ目",
    "祖母の涙――第2章前夜",
  ],
};

export const ui: Record<Locale, Record<string, string>> = {
  "zh-Hant": {
    project: "剴剴案特別專題",
    title: "沒有父母的孤兒",
    deck: "從一張舊竹椅，到一扇沒有及時打開的門",
    method: "觀察式紀錄片 × 文學化轉場 × 司法檔案查證 × 互動長卷",
    quote: "花有重開日，人無再少年。應須惜兒孫，安樂是天倫。",
    intro:
      "花謝了，尚有下一個春天；人的童年一旦過去，卻沒有誰能替他重新活過。本章以傳說提出問題，以紀錄查證事實，以一張空椅追問：在傷痕成為結局以前，誰能把門真正打開？",
    notice: "內容提醒：本專題涉及兒童死亡、虐待、急診與司法程序；不呈現傷勢照、遺體或真實哭喊。",
    source: "文學化皮影旁白｜非案件人物對話｜非真實錄音｜不代表法院認定",
    openStage: "幕開｜觀看序問",
    closeStage: "幕謝｜直接閱讀",
    map: "閱讀地圖",
    fullText: "完整正文",
    transition: "篇章轉場",
    playMusic: "播放本篇原創音樂",
    pauseMusic: "暫停音樂",
    musicCredit: "原創音樂由使用者提供；網站版約30秒，手動播放。",
    modes: "觀看方式",
    guided: "建議導覽",
    cinema: "完整電影版",
    reading: "直接閱讀",
    reduced: "減少動態",
    ending: "結尾皮影戲｜讓下一扇門更早打開",
    endingNote: "普通清晨沒有神蹟；只有有人願意在門外守候。",
    actionTitle: "若孩子此刻正處於危險",
    action:
      "立即危險或暴力請撥110；緊急傷病請撥119；疑似兒少虐待、疏忽或不當照顧，可撥113保護專線。",
    repository: "查看 GitHub 專案",
    specs: "製作規格與來源文件",
    transcript: "完整對話逐字稿",
    scroll: "向下閱讀",
  },
  "zh-Hans": {
    project: "剴剴案特别专题",
    title: "没有父母的孤儿",
    deck: "从一张旧竹椅，到一扇没有及时打开的门",
    method: "观察式纪录片 × 文学化转场 × 司法档案查证 × 互动长卷",
    quote: "花有重开日，人无再少年。应须惜儿孙，安乐是天伦。",
    intro:
      "花谢了，尚有下一个春天；人的童年一旦过去，却没有谁能替他重新活过。本章以传说提出问题，以纪录查证事实，以一张空椅追问：在伤痕成为结局以前，谁能把门真正打开？",
    notice: "内容提醒：本专题涉及儿童死亡、虐待、急诊与司法程序；不呈现伤势照、遗体或真实哭喊。",
    source: "文学化皮影旁白｜非案件人物对话｜非真实录音｜不代表法院认定",
    openStage: "幕开｜观看序问",
    closeStage: "幕谢｜直接阅读",
    map: "阅读地图",
    fullText: "完整正文",
    transition: "篇章转场",
    playMusic: "播放本篇原创音乐",
    pauseMusic: "暂停音乐",
    musicCredit: "原创音乐由使用者提供；网站版约30秒，手动播放。",
    modes: "观看方式",
    guided: "建议导览",
    cinema: "完整电影版",
    reading: "直接阅读",
    reduced: "减少动态",
    ending: "结尾皮影戏｜让下一扇门更早打开",
    endingNote: "普通清晨没有神迹；只有人愿意在门外守候。",
    actionTitle: "如果孩子此刻正处于危险",
    action: "立即危险或暴力请拨110；紧急伤病请拨119；疑似儿少虐待、疏忽或不当照顾，可拨113保护专线。",
    repository: "查看 GitHub 项目",
    specs: "制作规格与来源文件",
    transcript: "完整对话逐字稿",
    scroll: "向下阅读",
  },
  en: {
    project: "The Kaikai Case — Special Report",
    title: "An Orphan Without Parents",
    deck: "From an old bamboo chair to a door that did not open in time",
    method: "Observational documentary × literary transitions × judicial verification × interactive scroll",
    quote: "Flowers bloom again. Childhood does not return.",
    intro:
      "Flowers may meet another spring. A childhood, once lost, cannot be lived again. This chapter lets legend pose the question, records test the facts, and an empty chair ask who could have opened the door before injury became an ending.",
    notice: "Content note: child death, abuse, emergency care, and court proceedings. No injury, body, or authentic distress imagery is shown.",
    source: "Literary shadow-play narration | Not case dialogue | Not a recording | Not a court finding",
    openStage: "Raise curtain | Watch prologue",
    closeStage: "Lower curtain | Read directly",
    map: "Reading map",
    fullText: "Complete text",
    transition: "Chapter transition",
    playMusic: "Play original chapter score",
    pauseMusic: "Pause music",
    musicCredit: "Original music supplied by the project owner; web edit approximately 30 seconds, manual play only.",
    modes: "Viewing mode",
    guided: "Guided",
    cinema: "Cinema",
    reading: "Read only",
    reduced: "Reduced motion",
    ending: "Closing shadow play | Open the next door sooner",
    endingNote: "There is no miracle in the ordinary morning—only someone willing to wait outside the door.",
    actionTitle: "If a child is in danger now",
    action: "In Taiwan, call 110 for immediate violence, 119 for a medical emergency, or 113 for suspected child abuse, neglect, or improper care.",
    repository: "View GitHub project",
    specs: "Production specifications and source files",
    transcript: "Complete dialogue transcript",
    scroll: "Continue",
  },
  ja: {
    project: "剴剴事件 特別企画",
    title: "親のいない孤児",
    deck: "一脚の古い竹椅子から、間に合わなかった扉へ",
    method: "観察型ドキュメンタリー × 文学的転換 × 司法資料の検証 × インタラクティブ長編",
    quote: "花は再び咲いても、子どもの時間は戻りません。",
    intro:
      "花には次の春があります。しかし失われた子ども時代を、誰かが生き直すことはできません。伝承は問いを置き、記録は事実を確かめ、空の椅子は、傷が結末になる前に誰が扉を開けられたのかを問い続けます。",
    notice: "内容に関する注意：子どもの死亡、虐待、救急医療、司法手続を扱います。傷や遺体、実際の泣き声は提示しません。",
    source: "文学的な影絵の語り｜事件当事者の会話ではありません｜録音ではありません｜裁判所の認定ではありません",
    openStage: "開幕｜序問を見る",
    closeStage: "閉幕｜本文を読む",
    map: "読書マップ",
    fullText: "全文",
    transition: "章間トランジション",
    playMusic: "この章のオリジナル曲を再生",
    pauseMusic: "音楽を一時停止",
    musicCredit: "オリジナル音楽はプロジェクト所有者提供。ウェブ版は約30秒、手動再生のみ。",
    modes: "閲覧モード",
    guided: "ガイド",
    cinema: "映画版",
    reading: "本文のみ",
    reduced: "動きを減らす",
    ending: "終幕の影絵｜次の扉をもっと早く開くために",
    endingNote: "ありふれた朝に奇跡はありません。扉の外で待つ人がいるだけです。",
    actionTitle: "いま子どもが危険にある場合",
    action: "台湾では、差し迫った暴力は110、救急医療は119、虐待・ネグレクト・不適切な養育の疑いは113へ連絡してください。",
    repository: "GitHubプロジェクトを見る",
    specs: "制作仕様と資料",
    transcript: "対話全文",
    scroll: "続きを読む",
  },
};

export const prologueDialogue: Record<Locale, string[]> = {
  "zh-Hant": [
    "女｜簷前野花迎著風，謝了又開；庭中細草受了雨，倒下還能再起。為何春天年年都肯回來，一個孩子失去的年歲，卻再也沒有人替他送還？",
    "男｜我沿著六扇門走來，看見每扇門上都寫著職責；我翻過一層又一層卷宗，看見日期端正、姓名分明。只是那麼多人都說自己送過他一程，為何長路盡頭，仍沒有一雙手陪他走到明天？",
    "女｜莫說他年幼無言。春水不開口，尚能照見裂岸；幼兒不會陳情，身上的傷、消瘦的臉、退縮的眼睛，難道便不是話？",
    "男｜門內的人說一切安好，門外的人便把筆收起；一張表寫著已訪視，一通訊息寫著再確認。人們總相信下一個人會把事情完成，卻忘了孩子的一日，不能寄放在下一日。",
    "女｜那便把戲文暫歇，把卷宗放低一寸。不要問傳說裡的鬼神如何報應，只問活著的大人：看見以後有沒有追問，懷疑以後有沒有查證，危險逼近以前，有沒有把門真正打開。",
    "男｜今日所讀的不是誰的眼淚更重，也不是哪一句話更能激起眾怒。今日所讀，是一個仍然有人愛著的孩子，如何在大人各自完整的理由之間，失去他本來應有的明天。",
  ],
  "zh-Hans": [
    "女｜檐前野花迎着风，谢了又开；庭中细草受了雨，倒下还能再起。为什么春天年年都肯回来，一个孩子失去的年岁，却再也没有人替他送还？",
    "男｜我沿着六扇门走来，看见每扇门上都写着职责；我翻过一层又一层卷宗，看见日期端正、姓名分明。只是那么多人都说自己送过他一程，为什么长路尽头，仍没有一双手陪他走到明天？",
    "女｜莫说他年幼无言。春水不开口，尚能照见裂岸；幼儿不会陈情，身上的伤、消瘦的脸、退缩的眼睛，难道就不是话？",
    "男｜门内的人说一切安好，门外的人便把笔收起；一张表写着已访视，一则讯息写着再确认。孩子的一日，不能寄放在下一日。",
    "女｜那便把戏文暂歇，把卷宗放低一寸。只问活着的大人：看见以后有没有追问，怀疑以后有没有查证，危险逼近以前，有没有把门真正打开。",
    "男｜今日所读，是一个仍然有人爱着的孩子，如何在大人各自完整的理由之间，失去他本来应有的明天。",
  ],
  en: [
    "Woman | Wildflowers beneath the eaves meet the wind, wither, and bloom again. Why does spring return each year, while no one can return to a child the years he has lost?",
    "Man | I came by way of six doors and found a duty written upon each one. So many say they accompanied him for part of the journey. Why was there still no hand to lead him into tomorrow?",
    "Woman | Do not say that he was too young to speak. Spring water utters nothing, yet reveals the broken bank. Are his injuries, thinning face, and frightened withdrawal not also words?",
    "Man | Those inside said all was well, and those outside put down their pens. One day of a child’s life cannot be placed in the keeping of the next.",
    "Woman | Let the play fall silent and lower the files. Ask the living adults: after seeing, did they question; after doubting, did they verify; before danger closed in, did anyone open the door?",
    "Man | We are reading how a child who was still loved lost the tomorrow that should have been his, somewhere among the orderly reasons of adults.",
  ],
  ja: [
    "女｜軒先の野の花は風に揺れ、散ってはまた咲きます。春は毎年戻ってくるのに、なぜ一人の子どもが失った年月だけは、誰にも返せないのでしょう。",
    "男｜私は六つの扉をたどり、どの扉にも責務の文字があるのを見ました。誰もが道の途中までは彼を送ったと言うのに、なぜ明日まで手を引く人がいなかったのでしょう。",
    "女｜幼く、言葉がなかったなどと言わないでください。傷、痩せた顔、おびえて身を引くまなざしは、言葉ではないのでしょうか。",
    "男｜用紙には「訪問済み」、メッセージには「再確認」。けれど、子どもの一日を次の日に預けることはできません。",
    "女｜芝居を止め、記録を下げましょう。見た後に尋ねたか。疑った後に確かめたか。危険が迫る前に、本当に扉を開いたか。",
    "男｜今日読むのは、一人の子どもが大人たちの整った理由の間で、本来あるはずだった明日を失っていった、その経緯です。",
  ],
};

export const endingDialogue: Record<Locale, string[]> = {
  "zh-Hant": [
    "女｜戲將散了，燈也將熄。我們走過傳說、病房與法庭，留下來的，難道只能是一個孩子再也回不來的名字？",
    "男｜若卷宗只在悲劇以後證明誰曾經做錯，它便仍少了一頁；那一頁應當寫著，在危險成為結局以前，誰有責任依法啟動保護、及時把門打開。",
    "女｜花會重開，春天會回來。可是孩子失去的年歲，不能由下一季花期替他補還。",
    "男｜所以記住他，不是把他永遠留在最後一夜；是讓下一次傷痕出現時，有人相信，有人追問，有人不把今日寄放到明日。",
    "女｜也不要把保護交給傳說、運氣或某一個孤單的好人。讓每一次交接都能被確認，每一份職責都能走進門內。",
    "男｜那麼，請把這扇門推開。不是為了觀看悲傷，而是為了讓下一個孩子還來得及長大時，門外已經有人。",
  ],
  "zh-Hans": [
    "女｜戏将散了，灯也将熄。我们走过传说、病房与法庭，留下来的，难道只能是一个孩子再也回不来的名字？",
    "男｜如果卷宗只在悲剧以后证明谁曾经做错，它便仍少了一页；那一页应当写着，在危险成为结局以前，谁有责任依法启动保护、及时把门打开。",
    "女｜花会重开，春天会回来。可是孩子失去的年岁，不能由下一季花期替他补还。",
    "男｜所以记住他，是让下一次伤痕出现时，有人相信，有人追问，有人不把今日寄放到明日。",
    "女｜不要把保护交给传说、运气或某一个孤单的好人。让每一次交接都能被确认，每一份职责都能走进门内。",
    "男｜请把这扇门推开。不是为了观看悲伤，而是为了让下一个孩子还来得及长大时，门外已经有人。",
  ],
  en: [
    "Woman | The play is almost over, and the lamps will soon go dark. Must all that remains be the name of a child who can never return?",
    "Man | If the files can tell us only after tragedy who did wrong, then a page is still missing: who had a duty to activate protection and open the door in time?",
    "Woman | Flowers bloom again, and spring returns. But the years a child has lost cannot be restored by the flowers of another season.",
    "Man | To remember him is to ensure that when the next injury appears, someone believes, someone asks again, and no one places today in the keeping of tomorrow.",
    "Woman | Protection must not be entrusted to legend, luck, or one good person standing alone. Let every handover be confirmed, and every duty pass through the door.",
    "Man | Then open this door—not to look upon sorrow, but so that while the next child still has time to grow, someone is already waiting outside.",
  ],
  ja: [
    "女｜芝居は終わり、灯りもやがて消えます。残るものは、もう戻らない一人の子どもの名前だけなのでしょうか。",
    "男｜記録が悲劇の後に誰が誤ったかを示すだけなら、まだ一頁足りません。危険が結末になる前に、誰が保護を始動し、扉を開く責任を負っていたのか。",
    "女｜花は再び咲き、春は戻ります。けれど、子どもが失った年月を、次の季節の花で返すことはできません。",
    "男｜記憶するとは、次に傷が現れたとき、信じる人、問い直す人、今日を明日に預けない人がいるようにすることです。",
    "女｜守ることを伝承や運や、孤独な一人の善意に預けてはなりません。すべての引継ぎが確かめられるようにしましょう。",
    "男｜この扉を開いてください。悲しみを見るためではなく、次の子どもがまだ成長できるうちに、扉の外に誰かがいるようにするために。",
  ],
};

export const sceneObjects = ["竹椅／鬆動", "布帶／交接", "窗格／辨認", "布簾／傾聽", "活字／印記", "春聯／分界", "紅線／核實", "白髮／等待"];
